### ISSUE TITLE
Handle account lookup fails because of empty email error

### ISSUE THREAD

**Issue by kjakka** [NextJump/auth#32]
```
time="2019-05-08 13:11:22" level=error msg="[pkg/factory/auth.go#230] Error getting identity info for user [00216343]: 
Error executing service: https://10.100.100.211/v1/account/identity/lookup/00216343?org_id=1603
ORIGINAL STACK TRACE:
goroutine 206053 [running]:
pkg/client/http/otter.DoGet(0xc0021df3b0, 0x46, 0x0, 0x89a8a0, 0xc00b89fae0, 0x0, 0x0)
	/media/sf_nxj/dockervm/auth/src/pkg/client/http/otter/otter.go:87 +0x57d
pkg/client/http/otter.Get(0xc000025b60, 0x30, 0x89a8a0, 0xc00b89fae0, 0x2, 0xc000025b60)
	/media/sf_nxj/dockervm/auth/src/pkg/client/http/otter/otter.go:62 +0x113
pkg/provider.IdentityLookupInOrg(0xc00dd3f449, 0x8, 0x643, 0x0, 0x0, 0x865360, 0xc00da2bc20, 0x0)
	/media/sf_nxj/dockervm/auth/src/pkg/provider/auth.go:75 +0x127
pkg/factory.GetUserIdentity(0xc00dd3f449, 0x8, 0x643, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/media/sf_nxj/dockervm/auth/src/pkg/factory/auth.go:228 +0x7c
pkg/factory.SaveUserInfo(0x9b3da0, 0xc00e5ac700, 0xc01316b300, 0xc00dd3f449, 0x8, 0x643, 0x4, 0x0)
	/media/sf_nxj/dockervm/auth/src/pkg/factory/auth.go:70 +0xa6
pkg/controller.AuthIdentityHandler(0x9b3da0, 0xc00e5ac700, 0xc01316b300)
	/media/sf_nxj/dockervm/auth/src/pkg/controller/auth.go:99 +0x658
net/http.HandlerFunc.ServeHTTP(0x94c850, 0x9b3da0, 0xc00e5ac700, 0xc01316b300)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc013131720, 0x9b3da0, 0xc00e5ac700, 0xc01316b200)
	/media/sf_nxj/dockervm/auth/vendor/src/github.com/gorilla/csrf/csrf.go:267 +0x320
pkg/route.logMiddleware.func1(0x9b3da0, 0xc00e5ac700, 0xc01316b100)
	/media/sf_nxj/dockervm/auth/src/pkg/route/middleware.go:14 +0x83
net/http.HandlerFunc.ServeHTTP(0xc00b62ee80, 0x9b3da0, 0xc00e5ac700, 0xc01316b100)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001404d0, 0x9b3da0, 0xc00e5ac700, 0xc01316b100)
	/media/sf_nxj/dockervm/auth/vendor/src/github.com/gorilla/mux/mux.go:162 +0xf1
net/http.serverHandler.ServeHTTP(0xc00012e9c0, 0x9b3da0, 0xc00e5ac700, 0xc01316ae00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc011920640, 0x9b4420, 0xc00321bf40)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

otter error log
```
 /v1/account/identity/lookup/50221696
 Error executing query 
 	select
 	usr.pk_security_userid as ID,
 	usr.FName as Firstname,
 	usr.LName as Lastname,
 	usr.Username,
 	usr.Email,
 	usr.uniquehash as Hash,
 	org.pk_org_regid as OrgID,
 	org.name as OrgName,
 	isnull(lockedout, 0) as IsLocked
 	from tb_security_user usr with(nolock)
 	inner join tb_org_reg org with(nolock)
 	on usr.fk_pk_org_regid = org.pk_org_regid
 	where (usr.username = @id or usr.email = @id)
 	and (@oid = 0 or usr.fk_pk_org_regid = @oid)
 	and org.name <> ''
 	and uniquehash is not null
 	and available = 1
 	order by lastonsite desc, org.name 
 sql: Scan error on column index 4, name "Email": unsupported Scan, storing driver.Value type <nil> into type *string
 ORIGINAL STACK TRACE:
 goroutine 1259 [running]:
 nxj/lib/client/sql.FetchAll(0x157b5cc, 0x3, 0x126a100, 0xc000f13c60, 0x1657353, 0x240, 0xc000f13c80, 0x2, 0x2, 0x0, ...)
 	/otter/jenkins/workspace/OtterRelease_prod_release/src/nxj/lib/client/sql/sql.go:293 +0x635
 nxj/lib/client/sql/cpp.FetchAll(0x126a100, 0xc000f13c60, 0x1657353, 0x240, 0xc000b91228, 0x2, 0x2, 0xc000b6ac30, 0xc003a5c160)
 	/otter/jenkins/workspace/OtterRelease_prod_release/src/nxj/lib/client/sql/cpp/cpp.go:71 +0xae
 nxj/otter/app/v1_account/provider.UsernameLookup(0xc0004c5660, 0x8, 0x900, 0xc0004c5670, 0x4, 0xa, 0x40, 0x900)
 	/otter/jenkins/workspace/OtterRelease_prod_release/src/nxj/otter/app/v1_account/provider/user.go:43 +0x173
 nxj/otter/app/v1_account/factory.UsernameLookup(0xc0004c5660, 0x8, 0x900, 0x40, 0x900, 0x0, 0x0, 0x415f75)
 	/otter/jenkins/workspace/OtterRelease_prod_release/src/nxj/otter/app/v1_account/factory/user.go:26 +0x4f
 nxj/otter/app/v1_account/controller.IdentityLookup(0xc0004c5660, 0x8
```

**Comment by kjakka** [comment]
_Status changed to closed by commit cbf015_

**Comment by kjakka** [comment]
Otter side fix: https://gitlab.nextjump.com/nextjump/nxj-os/merge_requests/3702

**Comment by kjakka** [comment]
2nd fix from Otter side: https://gitlab.nextjump.com/nextjump/nxj-os/merge_requests/3703

**Comment by kjakka** [comment]
_mentioned in merge request !30_
